---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(readxl)
```

```{r}
dfPerson <- read_xlsx("../Final Project/persontrips.xlsx")
dfHousehold <- read_xlsx("../Final Project/Hhldtrips.xlsx")
dfPerson
dfHousehold
```

```{r}
#remove -1
dfPerson$driver[dfPerson$driver == -1] <- NA
dfPerson$educ[dfPerson$educ == -1 | dfPerson$driver == -7] <- NA
#driver == 1, no == 0
dfPerson$driver[dfPerson$driver == 2] <- 0
#worker == 1, not worker == 0
dfPerson$worker[dfPerson$worker == 2] <- 0
#male == 1, female == 0
dfPerson$r_sex[dfPerson$r_sex == 2] <- 0
#homeown == 1, rent == 0
dfPerson$homeown[dfPerson$homeown == 2] <- 0
dfHousehold$homeown[dfHousehold$homeown == 2] <- 0
#remove -7, -8, and -9 from hhincttl in both files
dfPerson$hhincttl[dfPerson$hhincttl >= -9 & dfPerson$hhincttl <= -7] <- NA
dfHousehold$hhincttl[dfHousehold$hhincttl >= -9 & dfHousehold$hhincttl <= -7] <- NA
#fix sub-zeros
dfPerson$r_age[dfPerson$r_age < 0] <- NA
dfPerson$worker[dfPerson$worker < 0] <- NA
dfPerson$educ[dfPerson$educ < 0] <- NA
dfHousehold$trpmiles[dfHousehold$trpmiles < 0] <- NA
```

```{r}
dfHousehold$incBin <- case_when(
  dfHousehold$hhincttl <= 6 ~ 1,
  dfHousehold$hhincttl >= 7 & dfHousehold$hhincttl <= 11 ~ 2,
  dfHousehold$hhincttl >= 12 & dfHousehold$hhincttl <= 16 ~ 3,
  dfHousehold$hhincttl >= 17 ~ 4
)

dfPerson$incBin <- case_when(
  dfPerson$hhincttl <= 6 ~ 1,
  dfPerson$hhincttl >= 7 & dfPerson$hhincttl <= 11 ~ 2,
  dfPerson$hhincttl >= 12 & dfPerson$hhincttl <= 16 ~ 3,
  dfPerson$hhincttl >= 17 ~ 4
)
```

```{r}
dfHousehold$sizeBin <- case_when(
  dfHousehold$hhsize == 1 ~ 1,
  dfHousehold$hhsize == 2 ~ 2,
  dfHousehold$hhsize == 3 ~ 3,
  dfHousehold$hhsize > 3 ~ 4
)

dfHousehold$vehBin <- case_when(
  dfHousehold$hhvehcnt == 0 ~ 0,
  dfHousehold$hhvehcnt == 1 ~ 1,
  dfHousehold$hhvehcnt == 2 ~ 2,
  dfHousehold$hhvehcnt == 3 ~ 3,
  dfHousehold$hhvehcnt > 3 ~ 4
)

dfHousehold$wrkBin <- case_when(
  dfHousehold$wrkcount == 0 ~ 0,
  dfHousehold$wrkcount == 1 ~ 1,
  dfHousehold$wrkcount > 2 ~ 2
)
```

```{r}
dfHousehold$vehRatio <- dfHousehold$hhvehcnt / dfHousehold$drvrcnt
dfHousehold$driverRatio <- dfHousehold$drvrcnt / dfHousehold$hhvehcnt
dfHousehold$distanceRatio <- dfHousehold$trpmiles / dfHousehold$drvrcnt
dfHousehold$sizeRatio <- dfHousehold$trpmiles / dfHousehold$hhsize
dfHousehold$adultRatio <- dfHousehold$numadlt / dfHousehold$hhsize
```

```{r}
dfPerson$educBin <- 0
dfPerson$educBin[dfPerson$educ > 1] <- 1

dfPerson$incRatio <- (dfPerson$hhincttl * 5000) / dfPerson$hhsize
dfPerson$adultRatio <- dfPerson$numadlt / dfPerson$hhsize

dfPerson$adult <- 0
dfPerson$adult[dfPerson$r_age >= 18] <- 1
```

```{r}
dfPerson
dfHousehold
```

```{r}
write_excel_csv(dfPerson, "../Final Project/dfPerson.csv")
write_excel_csv(dfHousehold, "../Final Project/dfHousehold.csv")
```
