---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(readxl)
```

```{r}
df <- read_xlsx("../Assignment 8/Assignment 8 Data.xlsx")
```


```{r}
#re-code access so no access is 0 instead of 2
df$access[df$access == 2] <- 0
```

```{r}
#re-code roadway functional class
#rural == 1, urban == 0
#interstate == 0, no interstate == 0
df$rural_road <- ifelse(df$class == 1 | df$class == 2, 1, 0)
df$interstate <- ifelse(df$class == 1 | df$class == 3, 1, 0)
```

```{r}
#re-code restrictions
#tonnage == 1, no tonnage restrictions == 0
#time == 1, no time restrictions == 0
#notrucks == 1, no truck restrictions == 0
df$tonnage <- ifelse(df$restrictions == 2 | df$restrictions == 4, 1, 0)
df$time <- ifelse(df$restrictions == 3 | df$restrictions == 4, 1, 0)
df$no_trucks <- ifelse(df$restrictions == 5, 1, 0)
```

```{r}
#determine that there are no rural counties with large populations
df %>%
  filter(county_pop > 50000 && locale == 1) %>%
  nrow()
#rural == 1, urban == 0
#small == 1, >50,000 == 0
df$rural <- ifelse(df$locale == 1, 1, 0)
df$small <- ifelse(df$locale == 1 | df$locale == 2, 1, 0)
```

```{r}
dfDummy <- df %>%
  select(aadt, county_pop, lanes, width, access, rural_road, interstate, tonnage, time, no_trucks, rural, small)
```
```{r}
#log transforms
dfDummy <- dfDummy %>%
  mutate(lnAADT = log(aadt))
```

```{r}
write_excel_csv(dfDummy, "../Assignment 8/Assignment 8 Data Mod.csv")
```

